### ISSUE TITLE
"Error sending request to GCM HTTP server" when registering a new client

### ISSUE THREAD

**Issue by ToddKerpelman** [googlesamples/friendlyping#6]
I'm receiving an error at the point where I start up my client app and it attempts to send a register_new_client message to my server. The Go server responds with...

```
Failed broadcasting the new client: error sending request to GCM HTTP server: error 
unmarshaling json from body: invalid character '<' looking for beginning of value
```

...and this is followed shortly afterwards with...

```
Failed sending client list: error sending request to GCM HTTP server: error 
unmarshaling json from body: invalid character '<' looking for beginning of value
```

Any idea what's going on? The client object that I'm sending across looks fairly normal, from what I can tell.

**Comment by silvolu** [comment]
Mmm, I tried to repro with a fresh install of everything, but I can't. Did you change anything?

**Comment by ToddKerpelman** [comment]
Nothing on the server. (And only the bundle ID, GoogleService-info.plist file, and the URL schemes on the client)

**Comment by ToddKerpelman** [comment]
Were you trying to repro with the Go server, or the Java one?

**Comment by silvolu** [comment]
Go server, which one are you using?

**Comment by ToddKerpelman** [comment]
Go also.

**Comment by silvolu** [comment]
Can you after [this line](https://github.com/googlesamples/friendlyping/blob/master/server/Go/server.go#L253):

```
gcm.DebugMode = true
```

And then run everything and show me what you got on screen?

**Comment by ToddKerpelman** [comment]
Will do. 

Incidentally, I've since tried out the Java server and have successfully gotten it to work (I've been pinging Larry Page all day, and he still don't return my messages), so I can confirm it seems to be a problem specific to the Go server.

**Comment by ToddKerpelman** [comment]
Ah. I think I've figured out the problem 

I was getting a 401 unauthorized error, and I finally realized that it's because I was copying-and-pasting the API_KEY value that I found in my info.plist value, and not the "Server API key" value from the console page. I had assumed they were the same value, but they're not.

**Comment by silvolu** [comment]
Yeah, that is confusing. I think your work on #7 makes it more clear, closing this.
