### ISSUE TITLE
iOS Client doesn't switch to Table View after signing in initially

### ISSUE THREAD

**Issue by ToddKerpelman** [googlesamples/friendlyping#8]
1. Start up a fresh app
2. Sign in.
3. Your console will tell you you've been signed in, but it also won't let you switch to the Table View with all the other pingable clients.
4. I also see a console error that looks like this: 2016-01-13 13:20:11.955 FriendlyPingSwift[1335:675208] Warning: Attempt to present <FriendlyPingSwift.FPViewController: 0x157755af0> on <SFSafariViewController: 0x1575f55d0> whose view is not in the window hierarchy!
5. Quitting the app and restarting it works fine. I'll be signed in automatically, and I'll jump into the TableVC

I'm assuming this is because we're attempting to transition to the next view controller while the embedded SFSafariVC is still being dismissed, or something like that. Let me fiddle with it a bit and see if I can come up with a decent pull request to fix it.

**Comment by silvolu** [comment]
I can reproduce, but I don't remember this happening when I wrote the app, wonder if it's been introduced by some recent version of SignIn.

**Comment by ToddKerpelman** [comment]
Possibly. Anyway, I have a fix that I can submit shortly.

**Comment by silvolu** [comment]
Thanks again!
